---
galaxy_info:
  author: Barush Mendez Ruan
  description: Perform system updates on Ubuntu servers
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
