- name: Join the K3s cluster
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k8s-cthulhu-1']['k3s_server_ip'] }}:6443 K3S_TOKEN={{ hostvars['k8s-cthulhu-1']['k3s_join_token'] }} sh -
  args:
    executable: /bin/bash
