- name: Install K3s on the control plane
  shell: |
    curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
  args:
    executable: /bin/bash

- name: Retrieve the K3s join token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false

- name: Save K3s join token
  set_fact:
    k3s_join_token: "{{ k3s_token.stdout }}"

- name: Gather control plane IP
  set_fact:
    k3s_server_ip: "{{ ansible_host }}"
